services:
  db:
    image: "postgis/postgis:latest"
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data     
    restart: always
    ports:
        - 5432:5432
volumes:
  db: